Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "fbilyS" do |control|
		control.vm.hostname = "fbilyS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "fbilyS"]
			v.memory = 1024
			v.cpus = 2
		end
		control.vm.provision "shell", inline: "chmod +x /vagrant/scripts/server.sh"
		control.vm.provision "shell", path: "./scripts/server.sh"
	end
  config.vm.define "fbilySW" do |control|
		control.vm.hostname = "fbilySW"
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "fbilySW"]
			v.memory = 1024
			v.cpus = 2
		end
		control.vm.provision "shell", inline: "chmod +x /vagrant/scripts/agent.sh"
		control.vm.provision "shell", path: "./scripts/agent.sh"
	end
end